# Generated by Django 4.1 on 2024-06-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_subscription_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Сессия"
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="amount",
            field=models.PositiveIntegerField(verbose_name="Сумма платежа"),
        ),
    ]
